config/routes.rb
Papersays::Application.routes.draw do
  resources :papers

  get "/" => "papers#index", :as => "root"

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  
  accepts_nested_attributes_for :questions, reject_if: proc { |attributes| attributes['content'].blank? }, :allow_destroy => true
  
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :paper
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, reject_if: proc { |attributes| attributes['content'].blank? }, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  def index
    @papers = Paper.all
  end

  def show
    @paper = Paper.find(params[:id])
  end

  def new
    @paper = Paper.new
    3.times do
      question = @paper.questions.build
      4.times { question.answers.build }
    end
  end

  def create
    @paper = Paper.new(paper_params)
    if @paper.save
      redirect_to @paper, :notice => "Successfully created paper."
    else
      render :action => 'new'
    end
  end

  def edit
    @paper = Paper.find(params[:id])
  end

  def update
    @paper = Paper.find(params[:id])
    if @paper.update_attributes(paper_params)
      redirect_to @paper, :notice  => "Successfully updated paper."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy
    redirect_to papers_url, :notice => "Successfully destroyed paper."
  end
  
  private
  
  def paper_params
    params.require(:paper).permit(:subject,:grade,:year,:_destroy, questions_attributes: [:id, :paper_id, :content, :_destroy, answers_attributes: [:id, :question_id, :content, :_destroy ]])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/papers/_answer_fields.html.erb
<p>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove" %>
</p>

app/views/papers/_form.html.erb
<%= form_for @paper do |f| %>
<%= f.error_messages %>
<p>
	<%= f.label :subject %>
	<br />
	<%= f.text_field :subject %>
</p>
<p>
	<%= f.label :grade %>
	<br />
	<%= f.text_field :grade %>
</p>
<p>
	<%= f.label :year %>
	<br />
	<%= f.text_field :year %>
</p>

<%= f.fields_for :questions do |builder| %>
<%= render 'question_fields', :f => builder %>

<% end %>

<p>
	<%= f.submit "Submit" %>
</p>
<% end %>

app/views/papers/_question_fields.html.erb
<p>
  <%= f.label :content, "Question" %><br />
  <%= f.text_area :content, :rows => 3 %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
</p>
<%= f.fields_for :answers do |builder| %>
  <%= render 'answer_fields', :f => builder %>
<% end %>

app/views/papers/edit.html.erb
<% title "Edit Paper" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @paper %> |
  <%= link_to "View All", papers_path %>
</p>

app/views/papers/index.html.erb
<% title "Papers" %>

<table>
  <tr>
    <th>Subject</th>
    <th>Grade</th>
    <th>Year</th>
  </tr>
  <% for paper in @papers %>
    <tr>
      <td><%= paper.subject %></td>
      <td><%= paper.grade %></td>
      <td><%= paper.year %></td>
      <td><%= link_to "Show", paper %></td>
      <td><%= link_to "Edit", edit_paper_path(paper) %></td>
      <td><%= link_to "Delete", paper, method: :delete, data: { confirm: "You sure?" } %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Paper", new_paper_path %></p>

app/views/papers/new.html.erb
<% title "New Paper" %>

<%= render 'form' %>

<p><%= link_to "Back to List", papers_path %></p>

app/views/papers/show.html.erb
<% title "Paper" %>

<p>
	<strong>Subject:</strong>
	<%= @paper.subject %>
</p>
<p>
	<strong>Grade:</strong>
	<%= @paper.grade %>
</p>
<p>
	<strong>Year:</strong>
	<%= @paper.year %>
</p>

<ol>
	<% @paper.questions.each do | question | %>
	<li>
		<%= question.content %>
	</li>
	<ul>
		<% question.answers.each do | answer | %>
		<li>
			<%= answer.content %>
			<div id="disqus_thread"></div>
			    <script type="text/javascript">
			        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
			        var disqus_shortname = 'prashnaapp'; // required: replace example with your forum shortname

			        /* * * DON'T EDIT BELOW THIS LINE * * */
			        (function() {
			            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
			            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
			            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
			        })();
			    </script>
			    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
			    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
			
		</li>
		<% end %>
	</ul>
	<% end %>
</ol>

<p>
	<%= link_to "Edit", edit_paper_path(@paper) %> |
	<%= link_to "Delete", @paper, method: :delete, data: { confirm: "You sure?" } %> |
	<%= link_to "View All", papers_path %>
</p>